model:
  base_learning_rate: 1e-04
  target: taming.models.vqgan.VQModelCTCAuxCond
  params:
    embed_dim: 256
    n_embed: 1664
    ddconfig:
      use_ctc_emb: false
      double_z: false
      z_channels: 256
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult:
      - 1
      - 1
      - 2
      - 2
      - 4
      num_res_blocks: 2
      attn_resolutions:
      - 16
      dropout: 0.0
    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminatorOCR
      params:
        disc_conditional: false
        disc_in_channels: 3
        disc_start: 10000
        disc_weight: 0.25
        disc_num_layers: 2
        codebook_weight: 1.0

        perceptual_weight: 0.2
        ocr_perceptual_weight: 1.0
    #ckpt_path: accum_grad_10_lessblank_ctc_pretrain/2023-02-23T13-13-10_ctc_pretrain/checkpoints/last.ckpt

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 1
    num_workers: 4
    train:
      target: taming.data.custom.CustomTextTrain
      params:
        training_images_list_file: /workspace/FigureEdit/PlotsLegend/matplots_img_train.txt
        size: 64
        random_crop: False
        augment: False
    validation:
      target: taming.data.custom.CustomTextTest
      params:
        test_images_list_file: /workspace/FigureEdit/PlotsLegend/matplots_img_test.txt
        size: 64
        random_crop: False
        augment: False
    test:
      target: taming.data.custom.CustomTextTest
      params:
        test_images_list_file: /workspace/FigureEdit/PlotsLegend/matplots_img_test.txt
        size: 64
        random_crop: False
        augment: False